goorm-369/893-back

- src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
- src/main/java/com/samyookgoo/palgoosam/auction/domain/Auction.java
- src/main/java/com/samyookgoo/palgoosam/auction/domain/AuctionImage.java
- src/main/java/com/samyookgoo/palgoosam/auction/domain/Category.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionCreateRequest.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/itemCondition.java
- src/main/java/com/samyookgoo/palgoosam/auction/file/FileStore.java
- src/main/java/com/samyookgoo/palgoosam/auction/file/ResultFileStore.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/CategoryRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
- src/main/java/com/samyookgoo/palgoosam/user/domain/User.java
- src/main/java/com/samyookgoo/palgoosam/user/repository/UserRepository.java
- src/main/resources/application.yml
경매 상품 등록
경매 상품 등록
경매 상품 이미지 등록
close #6
> Feat: 경매 상품 등록 기능 구현

- src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
- src/main/java/com/samyookgoo/palgoosam/auction/domain/AuctionImage.java
- src/main/java/com/samyookgoo/palgoosam/auction/domain/Category.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionCreateRequest.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionDetailResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionImageResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/ImageDto.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
- src/main/java/com/samyookgoo/palgoosam/user/domain/User.java
경매 상품 상세 조회
경매 제목, 상세 설명, 카테고리, 경매 상태, 경매 오픈 시간, 경매 종료 시간, 판매자 이메일, 경매 상태 조회
close #12
> Feat: 경매 상품 상세 조회 API 구현

- src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
- src/main/java/com/samyookgoo/palgoosam/auction/domain/Auction.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionCreateRequest.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionDetailResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionImageResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionUpdateRequest.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/ImageDto.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/itemCondition.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/CategoryRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
> Feat: 경매 상품 수정

- src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/ItemCondition.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
> Hotfix: import 추가 및 파일명 수정

- sql/init_mock_data.sql
- src/main/java/com/samyookgoo/palgoosam/auction/dto/itemCondition.java
- src/main/java/com/samyookgoo/palgoosam/search/controller/SearchHistoryController.java
- src/main/java/com/samyookgoo/palgoosam/search/dto/SearchHistoryResponseDto.java
- src/main/java/com/samyookgoo/palgoosam/search/service/SearchHistoryService.java
> fix: 검색 기록 조회 API 수정

- src/main/java/com/samyookgoo/palgoosam/auction/controller/ScrapController.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/ScrapService.java
- src/main/java/com/samyookgoo/palgoosam/user/domain/Scrap.java
- src/main/java/com/samyookgoo/palgoosam/user/repository/ScrapRepository.java
스크랩 하기 api 및 스크랩 취소하기 api
close #46 #47
> Feat: Scrap API 구현

- src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
- src/main/java/com/samyookgoo/palgoosam/bid/controller/SseController.java
- src/main/java/com/samyookgoo/palgoosam/bid/controller/response/BidEventResponse.java
- src/main/java/com/samyookgoo/palgoosam/bid/repository/BidRepository.java
- src/main/java/com/samyookgoo/palgoosam/bid/service/BidService.java
- src/main/java/com/samyookgoo/palgoosam/bid/service/SseService.java
- 실시간 입찰 정보 반영을 위해 Server-Sent Events(SSE)를 활용한 입찰 이벤트 브로드캐스트 기능을 추가했습니다.
- `SseService` 추가: 특정 경매에 연결된 클라이언트에게 입찰 이벤트 전송
- 입찰 생성, 입찰 취소 시 `BidEventResponse` 생성 및 SSE 전송
- 컨트롤러에서 이벤트 발생 시 `SseService.broadcastBidUpdate()` 호출
- 입찰 이벤트 전송을 위한 DTO `BidEventResponse` 정의
- `BidService`, `BidRepository` 리팩토링: 이벤트 데이터 구성을 위한 메서드 분리 및 개선
close #49
> Feat: 경매 실시간 입찰 정보 전송을 위한 SSE 기능 구현

- src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionListItemDto.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
- src/main/java/com/samyookgoo/palgoosam/user/domain/Scrap.java
- src/main/java/com/samyookgoo/palgoosam/user/repository/ScrapRepository.java
- 경매 기능에서 일부 함수가 누락되었거나 중복되어 동작에 영향을 주던 부분을 수정했습니다.
- 빠졌던 코드 추가 및 변수 타입 수정
- 중복된 어노테이션 제거
> Hotfix:  Auction 관련 누락된 코드 추가 및 중복 어노테이션 정리

- src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
- 기존에 임시로 사용하던 더미 유저를 제거하고, 실제 인증된 사용자를 BidController에 연동했습니다.
- `getDummyUser()` 메서드 제거
- 인증된 사용자 정보를 `AuthService`에서 받아와 입찰 관련 기능에 적용
- `placeBid`, `cancelBid` 메서드에서 실제 로그인된 유저의 ID 사용
> Feat: BidController에 인증된 사용자 연동

- src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
- src/main/java/com/samyookgoo/palgoosam/auction/controller/ScrapController.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionUpdateRequest.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionDetailResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionUpdatePageResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/CategoryResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/RelatedAuctionResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/file/FileStore.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
- src/main/java/com/samyookgoo/palgoosam/user/repository/ScrapRepository.java
연관 상품 목록 조회 
- 상세 페이지의 해당 상품과 연관된 상품 최대 10개 목록 조회
- 경매중인 상품만 조회
- 동일한 소분류 카테고리 상품 조회
- 동일한 소분류 카테고리가 10개 미만일 시 동일한 중분류 카테고리 상품 조회 
closes #16
> Feat 연관 상품 목록 조회 api 구현

- src/main/java/com/samyookgoo/palgoosam/notification/controller/NotificationController.java
- src/main/java/com/samyookgoo/palgoosam/notification/dto/NotificationResponseDto.java
- src/main/java/com/samyookgoo/palgoosam/notification/repository/NotificationStatusRepository.java
- src/main/java/com/samyookgoo/palgoosam/notification/service/NotificationService.java
- src/main/java/com/samyookgoo/palgoosam/notification/subscription/repository/AuctionSubscriptionRepository.java
- 삭제되지 않은 모든 알림을 가져오도록 로직을 작성했습니다.
- subscribtionType을 가져와 구매 알림인지, 판매 알림인지 구분할 수 있도록 했습니다.
- close #13
> Feat: 알림 내역 조회 API 구현

- src/main/java/com/samyookgoo/palgoosam/notification/controller/NotificationController.java
- src/main/java/com/samyookgoo/palgoosam/notification/repository/NotificationStatusRepository.java
- src/main/java/com/samyookgoo/palgoosam/notification/service/NotificationService.java
- 알림 소프트 삭제 기능을 추가했습니다.
- 로직은 이전 PR인 상태 업데이트와 완전히 같고 isDeleted만 변경됩니다.
이전 조회 PR에서는 40번이 마지막 알림이었는데 삭제처리 되었습니다.
- close #15
> Feat: 알림 삭제 API 구현

- src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
- src/main/java/com/samyookgoo/palgoosam/config/WebMvcConfig.java
WebMvcConfig 파일 추가
- WebMvcConfig 파일 추가
- CORS 허용 메서드에 PATCH 추가
> Feat: WebMvcConfig 파일 추가

- src/main/java/com/samyookgoo/palgoosam/payment/domain/Payment.java
- payment 엔티티 빠진 어노테이션 추가
- @Getter, @Setter
> Hotfix: Payment 엔티티 어노테이션 추가 

- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionImageResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
> Feat 이미지 업로드 오류 수정

- src/main/java/com/samyookgoo/palgoosam/PalgoosamApplication.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/scheduler/AuctionStatusScheduler.java
경매 상품 상태 전환 기능 구현
startTime이 현재 시간보다 이후이면 경매 상품 상태 pending -> active
endTime이 현재 시간보다 이후이면 경매 상품 상태 active -> completed
close #72
> Feat 경매 상품 상태 전환 기능 구현

- src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/ScrapService.java
로그인 유저 조회 로직 적용
더미데이터로 userId를 조회했었는데 로그인 구현 후 유저 조회 로직 적용
> Feat 로그인 유저 조회 로직 적용

- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionImageService.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
- src/main/java/com/samyookgoo/palgoosam/auth/service/AuthService.java
- src/main/java/com/samyookgoo/palgoosam/bid/projection/MainImageProjection.java
- src/main/java/com/samyookgoo/palgoosam/notification/controller/NotificationController.java
- src/main/java/com/samyookgoo/palgoosam/notification/fcm/service/FirebaseCloudMessageService.java
- src/main/java/com/samyookgoo/palgoosam/notification/service/NotificationService.java
- src/main/java/com/samyookgoo/palgoosam/notification/subscription/service/AuctionSubscriptionService.java
- src/main/java/com/samyookgoo/palgoosam/search/service/SearchHistoryService.java
- 입찰 내역 조회 시 이미지에서 NULL POINTER가 발생하는 버그 수정
> Bugfix: 입찰 내역 조회 시 이미지에서 NULL POINTER가 발생하는 버그 수정

- sql/init_mock_data.sql
- src/main/java/com/samyookgoo/palgoosam/payment/controller/PaymentController.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/request/PaymentConfirmRequest.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/response/PaymentConfirmResponse.java
- src/main/java/com/samyookgoo/palgoosam/payment/domain/Payment.java
- src/main/java/com/samyookgoo/palgoosam/payment/repository/PaymentRepository.java
- src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
- 클라이언트에서 Toss Payments에 결제 요청 후, 성공 리다이렉트 URL로 전달된 paymentKey, orderId, amount 정보를 서버로 전달하면
결제를 승인하고 결제 상태를 업데이트 및 응답하는 API 
- POST /api/payments/confirm 엔드포인트 추가
- Toss 결제 승인 API 연동
- 결제 승인 성공 시 주문/결제 정보 응답 및 필요 정보 DB에 저장
- 예외 발생 시 ResponseStatusException 기반으로 오류 응답 처리
close #70
> Feat: 경매 상품 결제 승인 API 구현

- src/main/java/com/samyookgoo/palgoosam/payment/controller/PaymentController.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/request/PaymentFailRequest.java
- src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
- Toss 결제 실패 발생 시, 클라이언트가 서버에 실패 정보를 전달하면 해당 결제를 FAILED 상태로 변경하는 API
- POST /api/payments/fail 엔드포인트 추가
- 클라이언트로부터 orderNumber, paymentKey, errorCode, errorMessage 수신
- 상태가 READY인 결제 건에 대해만 FAILED 상태로 변경
close #71
> Feat: 경매 상품 결제 실패 처리 API 구현

- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/RelatedAuctionResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/ScrapService.java
- src/main/java/com/samyookgoo/palgoosam/auth/controller/AuthController.java
- src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
- src/main/java/com/samyookgoo/palgoosam/deliveryaddress/controller/DeliveryAddressController.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/OrderController.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/PaymentController.java
- src/main/java/com/samyookgoo/palgoosam/user/controller/UserController.java
> Fix: 유저 널 체크 로직 추가

- src/main/java/com/samyookgoo/palgoosam/auth/JwtAuthenticationFilter.java
- src/main/java/com/samyookgoo/palgoosam/config/OAuth2AuthenticationFailureHandler.java
- src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
- 인증 화이트리스트 추가
- 더 직관적으로 인증을 통과할 URL을 볼 수 있도록 수정했습니다.
- 화이트리스트에 있는 URL 은 OAuth 인증 및 JWT 토큰 인증이 진행되지 않습니다.
- 일단은 SecurityConfig 및 JwtAuthenticateFilter 둘 다에 있는 화이트리스트에 경로를 추가해야 합니다.
- 추후에는 한 개의 파일로 분리 예정입니다.
> Hotfix: 인증 화이트리스트 추가

- src/main/java/com/samyookgoo/palgoosam/payment/controller/request/CreatePaymentRequest.java
- src/main/java/com/samyookgoo/palgoosam/payment/domain/PaymentMethod.java
- src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
> fix: fix payment feature

- src/main/java/com/samyookgoo/palgoosam/auth/JwtAuthenticationFilter.java
- src/main/java/com/samyookgoo/palgoosam/config/OAuth2AuthenticationFailureHandler.java
- src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
> fix: fix security config

- src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
> fix: add patch to SecurityConfig

- src/main/java/com/samyookgoo/palgoosam/auth/JwtAuthenticationFilter.java
- src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
> fix: fix authenticate filter

- src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
- 토스 페이먼츠 응답 파싱 과정에서 에러가 발생한 부분 수정
- OffesetDateTime 사용하여 결제 시간 파싱 완료
#70
> Hotfix: 경매 결제 승인 API 파싱 에러 수정

- build.gradle
- src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
- src/main/java/com/samyookgoo/palgoosam/auction/controller/ScrapController.java
- src/main/java/com/samyookgoo/palgoosam/auction/domain/Auction.java
- src/main/java/com/samyookgoo/palgoosam/auction/domain/AuctionImage.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionCreateResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionDetailResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionImageResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionUpdatePageResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionUpdateResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/CategoryResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/RelatedAuctionResponse.java
- src/main/java/com/samyookgoo/palgoosam/auth/JwtAuthenticationFilter.java
- src/main/java/com/samyookgoo/palgoosam/auth/controller/AuthController.java
- src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
- src/main/java/com/samyookgoo/palgoosam/bid/controller/SseController.java
- src/main/java/com/samyookgoo/palgoosam/common/response/BaseResponse.java
- src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
- src/main/java/com/samyookgoo/palgoosam/config/SwaggerConfig.java
- src/main/java/com/samyookgoo/palgoosam/deliveryaddress/controller/DeliveryAddressController.java
- src/main/java/com/samyookgoo/palgoosam/deliveryaddress/domain/DeliveryAddress.java
- src/main/java/com/samyookgoo/palgoosam/notification/controller/NotificationController.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/OrderController.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/PaymentController.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/response/OrderResponse.java
- src/main/java/com/samyookgoo/palgoosam/payment/domain/Payment.java
- src/main/java/com/samyookgoo/palgoosam/search/controller/SearchHistoryController.java
- src/main/java/com/samyookgoo/palgoosam/user/controller/UserController.java
- src/main/java/com/samyookgoo/palgoosam/user/domain/Scrap.java
- src/main/resources/application.yml
swagger 설정
controller에는 어노테이션 제가 추가해놨는데 맞게 썼는지 각자 api 확인 부탁드립니다
dto에는 스키마 어노테이션 붙이면 보기 편하다 해서 제꺼에는 붙여놨는데 원하신다면 각자 dto에 적용하시길 바랍니다.
> Feat: Swagger 설정

- src/main/java/com/samyookgoo/palgoosam/auction/controller/ScrapController.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionCreateRequest.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionDetailResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/ScrapService.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/response/OrderResponse.java
- src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
- src/main/java/com/samyookgoo/palgoosam/user/domain/Scrap.java
응답 dto 필드 정리 및 스크랩/결제 응답 개선
- 주문 조회페이지에서 구매자 필드 추가
- 상품 상세페이지에서 스크랩 필드명 수정 및 카테고리 id 필드 삭제
- 상품 등록 시 시작가 최대 1억 validation추가
- 스크랩 api 코드 리팩토링
> Feat: 응답 dto 필드 정리 및 스크랩/주문페이지 응답 개선

- src/main/resources/application.yml
이미지 관련 yml 파일 설정
단일 파일의 최대 크기 제한 및 요청 전체의 최대 크기 제한
> feat: 이미지 관련 yml 파일 설정

- src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
- 수정 반영이 안된 커밋이 있어서 에러가 발생했습니다.
- 수정을 마저 반영했습니다.
> Fix: auction service 에러 수정

- src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
- 인텔리제이가 리팩토링 후 경로 수정한 내용을 못 잡았네요. 수정해서 올렸습니다.
> Fix: 경매 컨트롤러 import 경로 수정

- src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionSearchRequestDto.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
- 쿼리문이 잘못되어 있어서 수정했습니다. 
- 예전에는 메서드로 불러와서 SpEL로 작성되어 있었으나, enum class로 통합하면서 문자열 검사로 수정했습니다. 
- 금액 관련하여 최대/최소 값이 설정되어 있지 않아 검증하는 로직을 추가했습니다.
=> 모든 작업은 Spring Security 관련 코드를 이전 PR로 롤백 후 작업했습니다.
> Fix: 검색 필터링이 적용되지 않던 버그 수정, 최대/최소 금액에 대한 검증 추가

- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/RelatedAuctionResponse.java
연관 상품 목록 응답 DTO 필드명 수정
close #119
> Fix: 연관 상품 목록 응답 DTO 필드명 및 구조 변경

- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionDetailResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/OrderController.java
- src/main/java/com/samyookgoo/palgoosam/payment/repository/PaymentRepository.java
- src/main/java/com/samyookgoo/palgoosam/payment/service/OrderService.java
- src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
주문 조회 로직 개선 및 낙찰자/결제 여부 응답 필드 추가
isCurrentUserBuyer, hasBeenPaid 필드 추가
close #123
> Feat: 주문 조회 로직 개선 및 낙찰자/결제 여부 응답 필드 추가

- src/main/java/com/samyookgoo/palgoosam/auction/controller/HomeController.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/home/DashboardResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/HomeService.java
홈 대쉬보드 API
- 현재 이용자 수 조회
- 총 등록된 경매 수 조회
- 현재 진행중인 경매 수 조회
close #125
> Feat: 홈 대쉬보드 API

- src/main/java/com/samyookgoo/palgoosam/auction/controller/HomeController.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/home/RecentAuctionResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/HomeService.java
- src/main/java/com/samyookgoo/palgoosam/user/repository/ScrapRepository.java
홈화면 최근 등록한 상품 목록 조회 (6개)
- createdAt 기준으로 조회
close #129
> Feat: 최근 등록한 상품 목록 조회 API 구현

- src/main/java/com/samyookgoo/palgoosam/auction/controller/HomeController.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/home/UpcomingAuctionResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/projection/AuctionScrapCount.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/HomeService.java
- src/main/java/com/samyookgoo/palgoosam/user/repository/ScrapRepository.java
경매 오픈이 임박한 상품 목록 조회 API 구현
close #131
> Feat 경매 오픈이 임박한 상품 목록 조회 API 구현

- src/main/java/com/samyookgoo/palgoosam/auction/controller/HomeController.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/HomeService.java
merge conflict 잡는중 중괄호를 같이 지워버려서 수정해서 올립니다(_ _)
> Fix: close missing brace in getRecentAuctions

- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionCreateResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
> Feat: AuctionCreateResponse에 auctionId 필드 추가

- src/main/java/com/samyookgoo/palgoosam/auction/controller/HomeController.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionSearchRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/HomeService.java
- src/main/java/com/samyookgoo/palgoosam/global/exception/GlobalExceptionHandler.java
여러 오류 수정
- GlobalHandlerException에 hidden 어노테이션 추가
- 대시보드 응답 형식 수정
- 검색 대표 이미지 쿼리 수정
- 이름 마스킹 하는 로직 수정
> Hotfix: 여러 오류 수정

- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionCreateResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/dto/response/CategoryResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/exception/AuctionCategoryException.java
- src/main/java/com/samyookgoo/palgoosam/auction/exception/AuctionForbiddenException.java
- src/main/java/com/samyookgoo/palgoosam/auction/exception/AuctionImageException.java
- src/main/java/com/samyookgoo/palgoosam/auction/exception/AuctionInvalidStateException.java
- src/main/java/com/samyookgoo/palgoosam/auction/exception/AuctionUpdateLockedException.java
- src/main/java/com/samyookgoo/palgoosam/auction/exception/CategoryNotFoundException.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
- src/main/java/com/samyookgoo/palgoosam/global/exception/ErrorCode.java
- src/main/java/com/samyookgoo/palgoosam/payment/exception/PaymentNotFoundException.java
경매 상품 관련 에러 핸들링 및 리팩토링
에러 핸들링을 먼저 하고 테스트 코드를 하려 했으나
테스트 코드를 작성하면서 에러 핸들링을 병행하는게 더 빠르고 낫다고 판단하여 일단 작업하던 것 먼저 pr 올립니다
> Refactor: 경매 상품 관련 에러 핸들링 및 리팩토링

- build.gradle
- src/main/java/com/samyookgoo/palgoosam/bid/domain/Bid.java
- src/main/java/com/samyookgoo/palgoosam/deliveryaddress/domain/DeliveryAddress.java
- src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
- src/main/java/com/samyookgoo/palgoosam/search/domain/SearchHistory.java
- src/test/resources/application-test.yml
도메인 객체의 @Builder.Default 누락 문제와 타입 안정성 부족 문제를 해결하고, 테스트 및 Jacoco 환경 설정을 개선했습니다. Gradle로 테스트 시 application-test.yml이 반영되지 않던 이슈도 함께 수정했습니다.
- @Builder.Default 누락 필드에 어노테이션 추가
- ObjectMapper.readValue에 TypeReference 사용
- @SuppressWarnings("unchecked") 제거
- gradle.properties에 spring.profiles.active=test 추가
- application-test.yml 설정 추가
- build.gradle의 test task에 프로필 전달 옵션 설정
- Jacoco 테스트 커버리지 리포트 및 검증 작업 설정 완료
- #167
> Chore: 빌더 기본값 및 타입 안정성 보완 + 테스트 및 Jacoco 환경 개선

- build.gradle
- Jacoco 연동은 완료되어 있으나 현재 커버리지율을 확인할 수 있는 `index.html` 파일이 생성되지 않는 문제가 발생하였습니다.
- gradle에 관련 설정 추가
- #175
> Chore: Gradle에 Jacoco 관련 설정 수정 및 추가

- src/main/java/com/samyookgoo/palgoosam/auction/dto/home/RecentAuctionResponse.java
- src/main/java/com/samyookgoo/palgoosam/auction/projection/DashboardProjection.java
- src/main/java/com/samyookgoo/palgoosam/auction/projection/RecentAuction.java
- src/main/java/com/samyookgoo/palgoosam/auction/projection/UpcomingAuction.java
- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
- src/main/java/com/samyookgoo/palgoosam/auction/service/HomeService.java
> Feat 홈 화면 리팩토링

- src/main/java/com/samyookgoo/palgoosam/payment/controller/response/OrderResponse.java
- src/main/java/com/samyookgoo/palgoosam/payment/service/OrderService.java
주문 조회 페이지에 customerName 필드 추가
close #171
> Feat 주문 조회 페이지에 구매자 필드 추가

- src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
- src/main/java/com/samyookgoo/palgoosam/bid/controller/request/BidRequest.java
- src/main/java/com/samyookgoo/palgoosam/bid/domain/Bid.java
- src/main/java/com/samyookgoo/palgoosam/bid/repository/BidRepository.java
- src/main/java/com/samyookgoo/palgoosam/bid/service/BidService.java
- src/test/java/com/samyookgoo/palgoosam/bid/controller/BidControllerTest.java
- src/test/java/com/samyookgoo/palgoosam/bid/controller/SseControllerTest.java
- src/test/java/com/samyookgoo/palgoosam/bid/repository/BidRepositoryTest.java
- src/test/java/com/samyookgoo/palgoosam/bid/service/BidServiceTest.java
- src/test/java/com/samyookgoo/palgoosam/bid/service/SseServiceTest.java
- 입찰 관련 Presentation / Business Layer 테스트 코드를 추가했습니다.
- BidControllerTest 작성
- SseControllerTest 작성
- SseServiceTest 작성
- BidServiceTest 테스트 케이스 추가 작성
- 불필요한 코드 제거
- #174
> Test: Bid 관련 Presentation / Business Layer 테스트 코드 추가

- src/main/java/com/samyookgoo/palgoosam/bid/domain/Bid.java
- src/main/java/com/samyookgoo/palgoosam/global/exception/ErrorCode.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/PaymentController.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/request/PaymentCreateRequest.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/request/TossPaymentConfirmRequest.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/request/TossPaymentFailCallbackRequest.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/response/PaymentCreateResponse.java
- src/main/java/com/samyookgoo/palgoosam/payment/controller/response/TossPaymentConfirmResponse.java
- src/main/java/com/samyookgoo/palgoosam/payment/domain/Payment.java
- src/main/java/com/samyookgoo/palgoosam/payment/policy/DeliveryPolicy.java
- src/main/java/com/samyookgoo/palgoosam/payment/repository/PaymentRepository.java
- src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
- src/test/java/com/samyookgoo/palgoosam/payment/service/PaymentServiceTest.java
-  PaymentService 테스트 코드 작성 및 리팩토링 하였습니다.
- PaymentService 에 대한 통합 테스트 코드 작성
- PaymentService 리팩토링
- #179
> Test: PaymentService  테스트 추가 및 리팩토링

- src/main/java/com/samyookgoo/palgoosam/bid/controller/response/BidResponse.java
- 입찰 내역 조회 시, 입찰자의 이메일이 그대로 노출되어 닉네임을 마스킹 처리해서 보내도록 수정했습니다.
- BidResponse에서 기존 입찰자의 이메일 가져오던 수 
- #182
> Feat: 입찰 내역 조회 시 입찰자 닉네임 마스킹 처리 추가

- src/test/java/com/samyookgoo/palgoosam/payment/controller/PaymentControllerTest.java
- src/test/java/com/samyookgoo/palgoosam/payment/repository/PaymentRepositoryTest.java
- PaymentController, PaymentRepository 테스트 코드 구현
- PaymentController 단위 테스트 구현
- PaymentRepository 단위 테스트 구현
- #184
> Test: PaymentController, PaymentRepository 테스트 코드 구현

- src/test/java/com/samyookgoo/palgoosam/bid/service/BidServiceTest.java
- 입찰 내역에서 입찰자의 이메일을 사용자 이름 + 마스킹 처리로 변경하면서 테스트 코드 수정이 필요해졌습니다.
- getEmail() -> getName() 으로 수정
- 마스킹 함수 적용
- #186
> Fix: BidServiceTest 입찰 내역의 입찰자 확인 부분 수정

- src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
- src/main/java/com/samyookgoo/palgoosam/bid/repository/BidRepository.java
- src/main/java/com/samyookgoo/palgoosam/user/service/UserService.java
- src/test/java/com/samyookgoo/palgoosam/auction/unit_test/AuctionRepositoryTest.java
- src/test/java/com/samyookgoo/palgoosam/bid/unit_test/BidRepositoryTest.java
- src/test/java/com/samyookgoo/palgoosam/payment/unit_test/PaymentRepositoryTest.java
- src/test/java/com/samyookgoo/palgoosam/user/integration_test/UserServiceBusinessLogicTest.java
- src/test/java/com/samyookgoo/palgoosam/user/unit_test/UserResponseDtoTest.java
- 마이페이지의 결제 내역, 입찰 내역, 경매 등록(판매자) 내역, 스크랩(찜) 내역에 대한 테스트 코드 작성
- 테스트를 작성하면서 고려하지 않았던 부분을 SQL에 반영(입찰 삭제, 경매 삭제)
주 테이블이 auction인데 bid 레포지토리에 위치한 두 개를 auction 레포지토리로 위치를 수정했습니다.
#153
> Test: User 도메인 리팩토링 및 테스트 코드 작성

- src/test/java/com/samyookgoo/palgoosam/bid/repository/BidRepositoryTest.java
- src/test/java/com/samyookgoo/palgoosam/bid/service/BidServiceTest.java
- src/test/java/com/samyookgoo/palgoosam/payment/repository/PaymentRepositoryTest.java
- src/test/java/com/samyookgoo/palgoosam/payment/service/PaymentServiceTest.java
- src/test/java/com/samyookgoo/palgoosam/search/integration_test/SearchHistoryServiceBusinessLogicTest.java
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE) 어노테이션을 추가해서 test.yml로 설정한 H2가 사용되도록 수정했습니다.
> Test: test코드의 DB 사용 설정 수정

- Dockerfile
- EC2 API 서버에 배포하기 위한 Dockerfile을 작성했습니다
- **Gradle 8.13**과 **Java 21**을 사용하여 Docker 컨테이너에서 실행할 수 있도록 Dockerfile을 작성했습니다.
- **JAR 파일**을 **Gradle 빌드** 후 **Docker 컨테이너** 내에서 실행할 수 있도록 설정했습니다.
- `EXPOSE 8080`을 추가하여 **포트 8080**을 열어 외부에서 애플리케이션에 접근할 수 있도록 했습니다.
- #191
> Chore: EC2 API 서버용 Dockerfile 작성

- .gitignore
- src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
- src/main/java/com/samyookgoo/palgoosam/config/OAuth2AuthenticationSuccessHandler.java
- src/main/java/com/samyookgoo/palgoosam/config/PropertyConfig.java
- src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
- src/main/java/com/samyookgoo/palgoosam/config/WebMvcConfig.java
- src/main/java/com/samyookgoo/palgoosam/deliveryaddress/controller/DeliveryAddressController.java
- src/main/java/com/samyookgoo/palgoosam/user/controller/UserController.java
- 코드 내 CORS 설정 등이 하드코딩되어 있던 것을 환경변수를 읽도록 수정
- yml을 환경변수가 읽을 수 있도록 수정
> Chore: env 파일 설정

- .github/workflows/deploy_palgoosam_api_server.yml
- CD 스크립트를 작성
프라이빗 인스턴스에 접근할 방법을 찾아보다가 EIC 엔드포인트를 통한 SSH 터널링이 된다는 것을 알게 되었습니다.
> chore: cd 스크립트 작성

- .github/workflows/deploy_palgoosam_api_server.yml
> fix: netcat 명시적으로 설치할 수 있도록 수정

- .github/workflows/deploy_palgoosam_api_server.yml
> fix: localhost를 IPv4 형태로 수정

- .github/workflows/deploy_palgoosam_api_server.yml
> Fix: deploy script debug

- .github/workflows/deploy_palgoosam_api_server.yml
> fix: ssh 수정

- src/test/resources/application-test.yml
- application.yml에 설정되어있는 ${SERVER_PORT}가 application.test.yml에 존재하지 않아 예외가 발생했습니다.
- application.test.yml에 가짜 서버 포트를 추가했습니다.
- #13
> Fix: application-test.yml 에 서버 포트 추가 

- .github/workflows/deploy_palgoosam_api_server.yml
> fix: yml생성 방법 수정

- src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
- src/main/java/com/samyookgoo/palgoosam/config/WebMvcConfig.java
> Hotfix: CORS 관련 수정

- src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
> Fix: Security Cors

- src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
- frontUrl 환경변수가 버셀 도메인으로 설정되어 로그인 리다이렉트시, 커스텀 도메인이 아닌 버셀 도메인으로 경로가 변경되는 문제가 발생했습니다.
- 환경변수를 커스텀 도메인으로 수정하고 연관되어 설정되어있던 SecurityConfig의 cors URL을 수정하였습니다.
> Hotfix: Login Redirect 문제 해결 

- src/main/java/com/samyookgoo/palgoosam/config/OAuth2AuthenticationSuccessHandler.java
- src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
- 현재 환경변수로만 등록되어있는 front end url을 yml 파일에 추가하여 환경변수에서 불러와 사용하도록 변경했습니다.
> Hotfix: front end url yml파일에 추가 

- src/main/java/com/samyookgoo/palgoosam/config/OAuth2AuthenticationSuccessHandler.java
- src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
> Hotfix: redirect url 환경변수 적용 안되는 이슈
